name: Repository Dispatch Workflow
on:
  workflow_dispatch:
    inputs:
      message:
        description: "Test message"
        required: true

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: ${{ inputs.message }}
        run: |
          echo "this is develop"
          echo "Message: $MESSAGE"
        env:
          MESSAGE: ${{ inputs.message }}
